### ISSUE TITLE
libprotobuf ERROR

### ISSUE THREAD

**Issue by ClemensLinnhoff** [DLR-TS/OSTAR-Quickstart#10]
I wanted to test adding another FMU. For that, I did the following steps:
- Download the [sl-1-0-sensor-model-repository-template from OpenMSL](https://github.com/openMSL/sl-1-0-sensor-model-repository-template/tree/main).
- Build it locally with statically linked protobuf as recommended in the [OSI documentation](https://opensimulationinterface.github.io/osi-antora-generator/asamosi/latest/interface/setup/installing_prerequisites.html#_linux). (I also tried bulding it with the Dockerfile4Model).
- Add the built FMU to models/fmu
- Copy the 01-opendrive-openscenario folder and change the configSimgleContainer.yml to use the sensor model template FMU:
  ```
  - simulator: CARLA
  autostart: true
  carla_host: localhost
  carla_port: 2000
  transaction_timeout: 1000
  do_step_timeout: 1000
  initialisation_timeout: 10000
  additional_parameters: "-ego hero -sr --resumeafter 5" # look up Configuration.md in Carla-OSI-Service for more options
  sensor_view_config:
  - base_name: OSMPSensor1 # Name must start with OSMP or OSI
    parent_name: hero
    sensor_type: camera
    sensor_mounting_position:
      x: -5
      y: 0
      z: 2
      roll: 0
      pitch: 0
      yaw: 0
    number_of_pixels_horizontal: 1280
    number_of_pixels_vertical: 720
    field_of_view_horizontal: 90
  - simulator: OSMP
    autostart: true
    model: "sl-1-0-sensor-model-repository-template.fmu"
    transaction_timeout: 5000
    do_step_timeout: 5000
    input:
      - {interface_name: "OSMPSensorView", base_name: "OSMPSensorView[0]"}
    output:
      - {interface_name: "OSMPSensorData", base_name: "OSMPSensorData[0]"}
  - simulator: OSMP
    autostart: true
    transaction_timeout: 5000
    do_step_timeout: 5000
    input:
      - {interface_name: "OSMPSensorViewCamera", base_name: OSMPSensor1} # Sensor1 sensorview contains camera data. Each image is saved with its timestamp and given interface_name.
      - {interface_name: "sl-1-0-sensor-model-repository-template", base_name: "OSMPSensorView[0]"}
      - {interface_name: "sl-1-0-sensor-model-repository-template", base_name: "OSMPSensorData[0]"}
  ```

Then I executed `./run.sh --visual` and selected my newly created scenario.
During execution I get the following protobuf error:

```
Nothing to read from OSMPSensorViewInConfigRequest
[libprotobuf ERROR /home/conan/w/prod-v1/bsr/57503/fafce/.conan/data/protobuf/3.21.9/_/_/build/b7d70226cb949f267607d279259074a5f57bbd98/src/src/google/protobuf/wire_format_lite.cc:618] String field 'CoSiMa.rpc.NamedString.value' contains invalid UTF-8 data when serializing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 
[libprotobuf ERROR /home/conan/w/prod-v1/bsr/57503/fafce/.conan/data/protobuf/3.21.9/_/_/build/b7d70226cb949f267607d279259074a5f57bbd98/src/src/google/protobuf/wire_format_lite.cc:618] String field 'CoSiMa.rpc.NamedString.value' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. 

terminate called after throwing an instance of 'std::exception'
  what():  std::exception
```
